name = "keen_cyan_cattle-2161"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "keen_cyan_cattle-2161-debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "keen_cyan_cattle-2161-release.wasm"
command = "npm run build:release"
